### ISSUE TITLE
Creazione pagina Wiki Activity Planning

### ISSUE THREAD

**Issue by giulitu95** [XNightHawk/SE2#21]
In quanto sviluppatore desidero una pagina Wiki che descriva la suddivisione del progetto in varie attività, ho bisogno inoltre di sapere quali attività verranno assegnate a ciascun componente del team di sviluppo in modo da conoscere i compiti e le features che devo sviluppare.

How to demo: lo sviluppatore accede alla pagina Wiki "Activity Planning", osserva le attività che gli sono state assegnate, procede quindi con lo svolgimento di esse.

**Comment by giulitu95** [comment]
Mi servirebbe sapere i nomi di chi si occupa delle varie attività 
@Booker1996 
@daniele122008 
@LucaZanella 
@simonelorengo 
@ST4CK-LP 
@XNightHawk

**Comment by XNightHawk** [comment]
Questo era quello che avevamo detto la scorsa volta che ne avevamo parlato

Lorenzo Bot
Daniele Bot + Front End
Simone Front End
Willi ML
Lorenzo Pilati DB
Turri Node
Luca Node

**Comment by giulitu95** [comment]
Perfetto grazie, ora aggiungo
