### ISSUE TITLE
Creazione pagina wiki Acceptance strategy

### ISSUE THREAD

**Issue by XNightHawk** [XNightHawk/SE2#4]
In quanto sviluppatore necessito di una pagina wiki riportante la acceptance strategy da seguire nel progetto in modo da poter valutare il successo del progetto a sviluppo terminato

How to demo: Aprendo la pagina wiki Acceptance strategy posso visionare i requisiti che il progetto dovra' soddisfare una volta ultimato

**Comment by giulitu95** [comment]
Sinceramente non mi viene in mente altro, sono stato sul più generale possibile dato che ad esempio non abbiamo ben definito quali saranno effettivamente i messaggi da inviare al bot, in caso vi venisse in mente altro da aggiungere,  scrivetemi o aggiornate voi

**Comment by XNightHawk** [comment]
Cosi' non credo vada bene, il punto di scrivere una acceptange strategy e' proprio quello di forzare a esplicitare tutti i dettagli non ancora esplicitati.

Bisogna definire i messaggi e le risposte del bot e definire esattamente la strutture e le funzionalita' dell'interfaccia web. Dovrebbe esserci un mock up per entrambe a questo punto.

Per quanto riguarda la parte di ML purtroppo non c'e' niente da scriverci nella acceptance strategy perche' e' puro back end. Mettiti d'accordo con chi si occupa del bot e dell'interfaccia dell'applicazione web per stabilire questi dettagli e scriverli tutti nella acceptance strategy nella maniera piu' precisa possibile.

@Booker1996 
@daniele122008 
@simonelorengo 
@giulitu95

**Comment by giulitu95** [comment]
Perfetto, ho visto che è stato caricato un breve mockup di alcune funzionalità su telegram, ora aggiorno la pagina definendo i comandi che ci sono sul mockup. Per quanto riguarda il mockup del sito si può fare qualcosa?
@simonelorengo

**Comment by giulitu95** [comment]
@simonelorengo  controlla se quello che ho scritto coincide con il tuo mockup e in caso fammi sapere, lascio intanto il lavoro nella sezione "Work in Progress".

**Comment by simonelorengo** [comment]
Ora controllo tutto e carico gli ultimi mokup con correzione grafica applicata e finisco la pagina Wiki.
Controllo ed eventualmente correggo, grazie intanto @giulitu95

**Comment by simonelorengo** [comment]
Perfetto, era tutto ok. 
Mi sono permesso di correggerti la dicitura "qr" in "QR Code" e impostare in H1 i titoli precedentemente in H2, al fine di uniformare lo stile con le altre pagine della Wiki.
Secondo me si può spostare in "Done".

**Comment by giulitu95** [comment]
Perfetto grazie mille!
