### ISSUE TITLE
Aggiunta attributo telegram_id nella tabella measures

### ISSUE THREAD

**Issue by LucaZanella** [XNightHawk/SE2#52]
In quanto sviluppatore desidero avere un attributo telegram_id all'interno della tabella measures del database in modo da poter identificare quale utente ha inserito la measure.

HTD: connettendomi al database uneatn e facendo la query: 

SELECT telegram_id
FROM measures

ottengo tutti i telegram id degli utenti che hanno inserito una measure.

**Comment by XNightHawk** [comment]
L'attributo verra' chiamato user_id in modo da non perdere in generalita'
