### ISSUE TITLE
Le emoji nella home page non visualizzano il grafico corretto

### ISSUE THREAD

**Issue by LucaZanella** [XNightHawk/SE2#59]
Cliccando su una emoji della home page questa apre sempre il grafico settimanale relativo al pasto lesto.

How to replicate: dopo aver aperto la cartella del backend e aver lanciato la bash di git, se si digita:
node HttpDispatcher.js
e si apre il browser in "http://localhost:8080/", cliccando su una qualsiasi delle emoji presente nella home page questa rimanda sempre al grafico settimanale del pasto lesto.

**Comment by simonelorengo** [comment]
All'interno della chiamata al redirect alla pagina del grafico settimanale, passavo un parametro con nome scorretto. "weekchart?canteen=x" è stato corretto con "weekchart?canteenId=x"
