### ISSUE TITLE
Aggiornamento interfaccia al database dopo sue modifiche

### ISSUE THREAD

**Issue by giulitu95** [XNightHawk/SE2#64]
E' necessario aggiornare gli helpers e le entities tenendo conto nel nuovo campo "codeName" del database nella tabella canteen in modo da poter rispondere con la lista di codeNames alla relativa richiesta.

How to Demo: Richiamo il metodo CanteenDBHelper e tramite una promise ottengo l'oggetto canteenEntity, tramite l'oggetto accedo così all'attributo codeName.

**Comment by LucaZanella** [comment]
Ho aggiornato CanteenEntity includendo la proprietà codeName. Inoltre ho aggiornato i metodi di CanteenDBHelper per fare in modo di instanziare un oggetto CanteenEntity passando anche il codeName e ho modificato, come stabilito, la funzione getCanteenByName rinominandola getCanteenByCodeName che prende in ingresso codeName anzichè name. Ho creato il branch node-canteen-codename sul quale ho fatto il commit e il successivo push delle mie modifiche. Attendo le modifiche al tuo codice prima di procedere al merge in development.
