### ISSUE TITLE
Chiamata API get best waiting time non produce il risultato corretto

### ISSUE THREAD

**Issue by XNightHawk** [XNightHawk/SE2#69]
La chiamata alla api /api/bestWaitingTime non produce risultati corretti

How to replicate: Inviare la richiesta

localhost:8080/api/bestWaitingTime?day=0&startTime=12:50&endTime=14:50

e osservare che per la mensa Pasto lesto questa ritorna un tempo di attesa minore che

localhost:8080/api/bestWaitingTime?day=0&startTime=12:00&endTime=14:50

che pero' si riferisce a un intervallo temporale piu' ampio

**Comment by LucaZanella** [comment]
All'interno del metodo del database invocavo in maniera sbagliata la funzione .getSeconds() omettendo le parentesi e ordinavo i risultati della query per arrive_time anzichè per wait_seconds.
