### ISSUE TITLE
Arrotondamento grafici

### ISSUE THREAD

**Issue by simonelorengo** [XNightHawk/SE2#75]
In quanto utente desidero che i grafici vengano mostrati in maniera piu' omogenea e con meno angoli.

How to demo: visualizzando le pagine corrispondenti al grafico comparativo o al grafico settimanale i grafici visualizzati appaiono come una linea continua e non spigolosa.

**Comment by XNightHawk** [comment]
Spostato in progress finche' la feature non e' testata e integrata sul branch development
