### ISSUE TITLE
Path errors relativi a file tpl

### ISSUE THREAD

**Issue by giulitu95** [XNightHawk/SE2#76]
Quando si avvia il server node all'esterno della cartella node_backend, node, per raggiungere i file tpl,  crea path omenttendo la directory "node_backend", non trovandoli, il server crasha

How to replicate: avvio il server node all'esterno della directory "node_backend" invocando il comando "node node_backend/HttpDispatcher.js", tramite browser apro la pagina home del front - end e mi accorgo che il server crasha con il seguente errore:
"no such file or directory, open ....SE2\web_interface\tpl\home.tpl"

**Comment by LucaZanella** [comment]
Ho modificato i path relativi ai file statici e ai template per fare in modo di lanciare l'applicazione da una directory esterna a node_backend
